baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '阿逸的GitHub小棧'
theme = "hugo-coder"
enableBackToTop = false
enableHeadingsAnchor = false
linkHeadingsToTOC = false
name = "阿逸"
email = "jikkzey02@gmail.com"
motto = "看我的，雷之一閃，六連！"
website = "https://matters.news/@mikejohn"
siteDescription = "這個網站存放阿逸的牢騷文..."
siteCreatedTime = "2021-12-10T20:17:43+00:00"
original = true
displayPublishedDate = false
displayExpiredDate = false
displayCategory = false
enableParagraphIndent = false
enableJustify = false
enablePostCopyright = true
enablePostShare = false
enablePostNav = true
enableFooter = true
displayCopyrightSymbol = true
displaySiteCreatedYear = true
displayPoweredBy = false
displaySiteCopyright = true

